/*********************************************************************************
 * 
 * Class Name:MSGDirectMessageUtilTest
 * Description: Test class to cover DirectMessageUtil class methods
 * Created By : Sameera De Silva
 * Created Date : 8/11/2020
 * 
 * Modification Log 
 * -------------------------------------------------------------------------------
 * Developer            Date			Description
 * 
 * 1. Sameera De Silva		8/11/2020  		Created the test class without body 	
 * ------------------------------------------------------------------------------- 					
 * 
 *********************************************************************************/

public class SNI_FL_DirectMessageUtilTest {

}