/********************************************************************************* 
Class Name     : MSGDirectMessageUtil.cls
Description    : 
Created By     : 
Created Date   : 

Modification Log
---------------------------------------------------------------------------------- 
Developer                   Date                   Description

1.Sameera De Silva			8/11/2020				Created class without body
----------------------------------------------------------------------------------            

*********************************************************************************/

public class SNI_FL_DirectMessageUtil {

}