@isTest private class TestController {

   /* static testMethod void testfetchLookUpValues() {
        string searchKeyWord = 'TEST';
    	string ObjectName = 'Account';
        
        List <sObject> resList = customLookUpController.fetchLookUpValues(searchKeyWord , ObjectName);
        system.assertEquals(true, resList.size() > 0);
    }
    
    static testMethod void testDirectMessageUtil() {
        
    }  */

}